repos:
  - repo: local
    hooks:
    -   id: checking
        name: checking
        entry: make
        args: ["check"]
        language: system
        pass_filenames: false
    -   id: formatting
        name: formatting
        entry: make
        args: ["format"]
        language: system
        pass_filenames: false