# configs/bc.yaml
# Hydra configuration for Behavioral Cloning pre-training

# Data configuration
data:
  training_data_dir: '${hydra:runtime.cwd}/trajectory_data'
  test_size: 0.2
  random_state: 42

# Environment configuration
env:
  # Gymnasium environment to train on (should match the environment used for trajectory generation)
  name: MiniGrid-DoorKey-6x6-v0
  max_episode_steps: 360

# Global random seed
seed: 42

# Whether to use CUDA for training
cuda: true

# Model configuration
model:
  # Network architecture
  hidden_size: 64
  # Learning rate
  lr: 2.5e-4 

# Training configuration
train:
  # Training parameters
  num_epochs: 50
  batch_size: 32

  # Model saving
  save_path: '${hydra:runtime.cwd}/bc_model.pth'

  # Evaluation settings
  eval_max_steps: 100

# Logging configuration (optional)
logging:
  # Whether to print detailed training progress
  verbose: true
  # Print frequency (every N epochs)
  print_freq: 10
